name: test-backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: setup-conda
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pipeline-profiles
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - run: |
          conda info
          conda list
          cd src/data_management
          python tests.py
